name: PR Visual Snapshot Updates
on:
  workflow_run:
    workflows: [PR Build]
jobs:
  pr-visual-snapshot-updates:
    if: ${{github.event.workflow_run.conclusion == 'failure'}}
    name: PR Visual Snapshot Updates
    runs-on: ubuntu-latest
    steps:
      - name: Download Changes
        uses: dawidd6/action-download-artifact@v2
        with:
          name: visual-snapshot-update.diff
          path: visual-snapshot-update.diff
          workflow: ${{github.event.workflow_run.workflow_id}}
          run_id: ${{github.event.workflow_run.id}}
          if_no_artifact_found: ignore
      - name: Push Changes
        id: push-changes
        run: |
          upstream=https://github.com/${{github.repository}}.git
          updateBranchName=vrt-update/pr-${{inputs.pr-number}}

          if test -f visual-snapshot-update.diff
            # configure git
            git config user.name "GitHub"
            git config user.email "noreply@github.com"

            # apply changes
            cat visual-snapshot-update.diff | git apply
            rm visual-snapshot-update.diff

            # commit changes
            git add .
            git commit --message 'chore: update vrt snapshots for `${{inputs.pr-branch}}`'

            # push changes
            git push $upstream head:refs/heads/$updateBranchName --force

            # set step outputs
            echo "commit-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          then
          else
            # delete branch if it exists
            git push $upstream -d $updateBranchName || echo "branch doesn't exit"
          fi
      - name: Get PR Event
        id: get-pr-event
        if: ${{steps.push-changes.outputs.commit-sha}}
        uses: potiuk/get-workflow-origin@v1_3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          sourceRunId: ${{github.event.workflow_run.id}}
      - name: Visual Regression Test Failed PR Comment
        if: ${{steps.push-changes.outputs.commit-sha}}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{steps.get-pr-event.outputs.pullRequestNumber}}
          body: |
            👋 @${{github.event.sender.login}},

            This PR introduces visual changes: ${{steps.push-visual-snapshot-updates.outputs.status.commit-sha}}
            If these changes are intended and correct, please cherry-pick the above commit to this PR.

            ```
            git checkout ${{steps.get-pr-event.outputs.sourceHeadBranch}}
            git fetch https://github.com/${{github.repository}}.git ${{steps.push-visual-snapshot-updates.outputs.status.commit-sha}}
            git cherry-pick ${{steps.push-visual-snapshot-updates.outputs.status.commit-sha}}
            git push
            ```

            Thank you,

            🤖 Clarity Visual Regression Test Bot
          edit-mode: replace
