name: Update Prebuilt Branches
on:
  push:
    branches:
      - main
      - next
      - beta
permissions:
  contents: write
concurrency:
  group: update-prebuilt-branches
  cancel-in-progress: true
jobs:
  update-prebuilt-branches:
    name: Update Prebuilt Branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Disable Docs Builds
        run: node ./scripts/clear-npm-script.js _build:demo _build:storybook
      - name: Build
        run: npm run build
      - name: Update Prebuilt Branches
        env:
          GIT_BRANCH: ${{github.ref_name}}
          GIT_COMMIT_SHA: ${{github.sha}}
        run: ./scripts/update-prebuilt-branches.sh
