name: Update Prebuilt Branches
on:
  push:
    branches: main
jobs:
  update-prebuilt-branches:
    name: Update Prebuilt Branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Update Prebuilt Branches
        run: ./scripts/update-prebuilt-branches.sh
